### ISSUE TITLE
Huge amounts of text missing on long chats?

### ISSUE THREAD

**Issue by cantonalex** [rohit1kumar/shareclaude#2]

**Comment by rohit1kumar** [comment]
Can you share some screenshots? If you are referring to artifacts, then yes, It does not support it yet, but I am working on it.

**Comment by cantonalex** [comment]
No it wasnt artifacts

**Comment by rohit1kumar** [comment]
Hi @cantonalex  I've updated the extension & site, hopefully no more missing text 🤞 waiting for Chrome Store approval. 

- Updates: [feat/new-ui](https://github.com/rohit1kumar/shareclaude/tree/feat/new-ui)  
- Staging URL: [https://feat-new-ui.shareclaude.pages.dev/](https://feat-new-ui.shareclaude.pages.dev)
