### ISSUE TITLE
MINOR:  Clarify data-flow / privacy in README (and Website)

### ISSUE THREAD

**Issue by Justin-Maxwell** [rohit1kumar/shareclaude#7]
It might be worth clarifying where the content actually goes in the process.  I'm all but certain it's how I would expect (that it's just a random ID native to Claude being exposed in the URL, and that the ID is coming from the Claude API, but I don't know that, and it's not mentioned.

For example - for all I know (without digging) it's possible that the actual conversation text is being pulled by the plugin, being stored in your private cloud DB somewhere, an ID assigned by the plugin, and the sharing being served not from Claude but from your DB.

Okay I could (and will in a moment) check the resources called by the browser at the served shared link URL.  But that (or anything) shouldn't be needed for a casual non-developer wanting to use your (lovely, awesome, really cool, much appreciated, simple and delightful, problem-solving) browser-extension.

Please don't see this as any sort of criticism, it's NOT.  It's just me seeing a simple improvement that would have made my use of your extension even more frictionless!

**Comment by rohit1kumar** [comment]
thanks for the suggestion I have updated the change on PR #8
